import { loadEnvConfig } from "@next/env";
import { writeFileSync, existsSync, chmodSync } from "fs";
import { randomBytes } from "crypto";
import { join } from "path";
import webPush from "web-push";

const projectDir = process.cwd();

// Load .env.example to understand structure
loadEnvConfig(projectDir, false);

const envLocalPath = join(projectDir, ".env.local");

// Refuse to overwrite existing .env.local
if (existsSync(envLocalPath)) {
  console.error("❌ .env.local already exists. Will not overwrite.");
  console.error(
    "   If you need to regenerate secrets, delete .env.local first."
  );
  process.exit(1);
}

console.log("🔐 Generating secrets for PashuSeva...\n");

// Generate cryptographically secure secrets
const sessionSecret = randomBytes(32).toString("base64");
const pinPepper = randomBytes(32).toString("base64");

const vapidKeys = webPush.generateVAPIDKeys();

console.log("✅ Generated SESSION_SECRET (32 bytes)");
console.log("✅ Generated PIN_PEPPER (32 bytes)");
console.log("✅ Generated VAPID Keys for Web Push\n");

// Create .env.local content
const envContent = `# Generated by scripts/setup-env.ts on ${new Date().toISOString()}
# DO NOT COMMIT THIS FILE

NODE_ENV=development

APP_ORIGIN=http://localhost:3000

# Database connection strings
# IMPORTANT: Update these with your actual database credentials
DATABASE_URL=postgresql://pashuseva:change_me_local_only@localhost:5432/pashuseva
TEST_DATABASE_URL=postgresql://pashuseva:change_me_local_only@localhost:5432/pashuseva_test

DB_SPATIAL_MODE=auto

# Generated secrets (keep these safe)
SESSION_SECRET=${sessionSecret}
PIN_PEPPER=${pinPepper}

SESSION_ISSUER=pashuseva
SESSION_AUDIENCE=pashuseva-web

TRUST_PROXY_HOPS=0

NEXT_PUBLIC_APP_NAME=PashuSeva
NEXT_PUBLIC_OSM_TILE_URL=https://tile.openstreetmap.org/{z}/{x}/{y}.png

# Development seed opt-in (set to true only for local development)
ALLOW_DEMO_SEED=false

# Demo PINs (set 4-digit PINs if you want to seed demo accounts)
DEMO_FARMER_PIN=
DEMO_VET_PIN=
DEMO_PARAVET_PIN=

# Web Push Keys
VAPID_SUBJECT=mailto:admin@pashuseva.local
VAPID_PRIVATE_KEY=${vapidKeys.privateKey}
NEXT_PUBLIC_VAPID_PUBLIC_KEY=${vapidKeys.publicKey}
`;

// Write .env.local
writeFileSync(envLocalPath, envContent, { mode: 0o600 });

// Attempt to set restrictive permissions (works on Unix-like systems)
try {
  chmodSync(envLocalPath, 0o600);
  console.log("✅ Created .env.local with restrictive permissions (0600)\n");
} catch (err) {
  console.log("✅ Created .env.local\n");
  console.log(
    "⚠️  Note: Could not set file permissions (Windows limitation)"
  );
  console.log(
    "   Ensure .env.local is not committed to version control\n"
  );
}

console.log("📝 Next steps:");
console.log("");
console.log("1. Review .env.local and update DATABASE_URL with your credentials");
console.log("2. Start PostgreSQL:");
console.log("   docker compose up -d");
console.log("");
console.log("3. Run migrations:");
console.log("   npm run db:migrate");
console.log("");
console.log("4. (Optional) Enable PostGIS:");
console.log("   npm run db:spatial");
console.log("");
console.log("5. (Optional) Seed demo data:");
console.log("   - Set ALLOW_DEMO_SEED=true in .env.local");
console.log("   - Set DEMO_FARMER_PIN, DEMO_VET_PIN, DEMO_PARAVET_PIN");
console.log("   - Run: npm run db:seed");
console.log("");
console.log("6. Start development server:");
console.log("   npm run dev");
console.log("");
console.log("⚠️  IMPORTANT: Never commit .env.local to git");
console.log("   It contains secrets and should remain private.");
